// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workerapi.proto

package workerapipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DequeueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pull endpoint path (same route selector used by HTTP Pull API).
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Optional; defaults to 1 and is capped by server policy.
	Batch uint32 `protobuf:"varint,2,opt,name=batch,proto3" json:"batch,omitempty"`
	// Optional dequeue wait and lease values.
	MaxWait       *durationpb.Duration `protobuf:"bytes,3,opt,name=max_wait,json=maxWait,proto3" json:"max_wait,omitempty"`
	LeaseTtl      *durationpb.Duration `protobuf:"bytes,4,opt,name=lease_ttl,json=leaseTtl,proto3" json:"lease_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueRequest) Reset() {
	*x = DequeueRequest{}
	mi := &file_workerapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRequest) ProtoMessage() {}

func (x *DequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRequest.ProtoReflect.Descriptor instead.
func (*DequeueRequest) Descriptor() ([]byte, []int) {
	return file_workerapi_proto_rawDescGZIP(), []int{0}
}

func (x *DequeueRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DequeueRequest) GetBatch() uint32 {
	if x != nil {
		return x.Batch
	}
	return 0
}

func (x *DequeueRequest) GetMaxWait() *durationpb.Duration {
	if x != nil {
		return x.MaxWait
	}
	return nil
}

func (x *DequeueRequest) GetLeaseTtl() *durationpb.Duration {
	if x != nil {
		return x.LeaseTtl
	}
	return nil
}

type DequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DequeueItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueResponse) Reset() {
	*x = DequeueResponse{}
	mi := &file_workerapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueResponse) ProtoMessage() {}

func (x *DequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueResponse.ProtoReflect.Descriptor instead.
func (*DequeueResponse) Descriptor() ([]byte, []int) {
	return file_workerapi_proto_rawDescGZIP(), []int{1}
}

func (x *DequeueResponse) GetItems() []*DequeueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DequeueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	NextRunAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	Route         string                 `protobuf:"bytes,6,opt,name=route,proto3" json:"route,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Trace         map[string]string      `protobuf:"bytes,9,rep,name=trace,proto3" json:"trace,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueItem) Reset() {
	*x = DequeueItem{}
	mi := &file_workerapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueItem) ProtoMessage() {}

func (x *DequeueItem) ProtoReflect() protoreflect.Message {
	mi := &file_workerapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueItem.ProtoReflect.Descriptor instead.
func (*DequeueItem) Descriptor() ([]byte, []int) {
	return file_workerapi_proto_rawDescGZIP(), []int{2}
}

func (x *DequeueItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DequeueItem) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *DequeueItem) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *DequeueItem) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DequeueItem) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *DequeueItem) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *DequeueItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DequeueItem) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DequeueItem) GetTrace() map[string]string {
	if x != nil {
		return x.Trace
	}
	return nil
}

type AckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pull endpoint path.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Exactly one of lease_id or lease_ids must be set.
	LeaseId       string   `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseIds      []string `protobuf:"bytes,3,rep,name=lease_ids,json=leaseIds,proto3" json:"lease_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_workerapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_workerapi_proto_rawDescGZIP(), []int{3}
}

func (x *AckRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AckRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *AckRequest) GetLeaseIds() []string {
	if x != nil {
		return x.LeaseIds
	}
	return nil
}

type NackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pull endpoint path.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Exactly one of lease_id or lease_ids must be set.
	LeaseId  string   `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseIds []string `protobuf:"bytes,3,rep,name=lease_ids,json=leaseIds,proto3" json:"lease_ids,omitempty"`
	// Ignored when dead=true.
	Delay         *durationpb.Duration `protobuf:"bytes,4,opt,name=delay,proto3" json:"delay,omitempty"`
	Dead          bool                 `protobuf:"varint,5,opt,name=dead,proto3" json:"dead,omitempty"`
	Reason        string               `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_workerapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_workerapi_proto_rawDescGZIP(), []int{4}
}

func (x *NackRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *NackRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *NackRequest) GetLeaseIds() []string {
	if x != nil {
		return x.LeaseIds
	}
	return nil
}

func (x *NackRequest) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *NackRequest) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

func (x *NackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ExtendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pull endpoint path.
	Endpoint      string               `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	LeaseId       string               `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ExtendBy      *durationpb.Duration `protobuf:"bytes,3,opt,name=extend_by,json=extendBy,proto3" json:"extend_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendRequest) Reset() {
	*x = ExtendRequest{}
	mi := &file_workerapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendRequest) ProtoMessage() {}

func (x *ExtendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workerapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendRequest.ProtoReflect.Descriptor instead.
func (*ExtendRequest) Descriptor() ([]byte, []int) {
	return file_workerapi_proto_rawDescGZIP(), []int{5}
}

func (x *ExtendRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ExtendRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ExtendRequest) GetExtendBy() *durationpb.Duration {
	if x != nil {
		return x.ExtendBy
	}
	return nil
}

type AckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of successful acks. Includes idempotent duplicate retries.
	Acked         uint32           `protobuf:"varint,1,opt,name=acked,proto3" json:"acked,omitempty"`
	Conflicts     []*LeaseConflict `protobuf:"bytes,2,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_workerapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_workerapi_proto_rawDescGZIP(), []int{6}
}

func (x *AckResponse) GetAcked() uint32 {
	if x != nil {
		return x.Acked
	}
	return 0
}

func (x *AckResponse) GetConflicts() []*LeaseConflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type NackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of successful nack/dead operations. Includes idempotent retries.
	Succeeded     uint32           `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Conflicts     []*LeaseConflict `protobuf:"bytes,2,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackResponse) Reset() {
	*x = NackResponse{}
	mi := &file_workerapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackResponse) ProtoMessage() {}

func (x *NackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workerapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackResponse.ProtoReflect.Descriptor instead.
func (*NackResponse) Descriptor() ([]byte, []int) {
	return file_workerapi_proto_rawDescGZIP(), []int{7}
}

func (x *NackResponse) GetSucceeded() uint32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *NackResponse) GetConflicts() []*LeaseConflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type LeaseConflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Expired       bool                   `protobuf:"varint,2,opt,name=expired,proto3" json:"expired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseConflict) Reset() {
	*x = LeaseConflict{}
	mi := &file_workerapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseConflict) ProtoMessage() {}

func (x *LeaseConflict) ProtoReflect() protoreflect.Message {
	mi := &file_workerapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseConflict.ProtoReflect.Descriptor instead.
func (*LeaseConflict) Descriptor() ([]byte, []int) {
	return file_workerapi_proto_rawDescGZIP(), []int{8}
}

func (x *LeaseConflict) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseConflict) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

var File_workerapi_proto protoreflect.FileDescriptor

const file_workerapi_proto_rawDesc = "" +
	"\n" +
	"\x0fworkerapi.proto\x12\x12hookaido.worker.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\x0eDequeueRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05batch\x18\x02 \x01(\rR\x05batch\x124\n" +
	"\bmax_wait\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\amaxWait\x126\n" +
	"\tlease_ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bleaseTtl\"H\n" +
	"\x0fDequeueResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.hookaido.worker.v1.DequeueItemR\x05items\"\xfb\x03\n" +
	"\vDequeueItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12:\n" +
	"\vnext_run_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x12\x14\n" +
	"\x05route\x18\x06 \x01(\tR\x05route\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12F\n" +
	"\aheaders\x18\b \x03(\v2,.hookaido.worker.v1.DequeueItem.HeadersEntryR\aheaders\x12@\n" +
	"\x05trace\x18\t \x03(\v2*.hookaido.worker.v1.DequeueItem.TraceEntryR\x05trace\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"TraceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\n" +
	"AckRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1b\n" +
	"\tlease_ids\x18\x03 \x03(\tR\bleaseIds\"\xbe\x01\n" +
	"\vNackRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1b\n" +
	"\tlease_ids\x18\x03 \x03(\tR\bleaseIds\x12/\n" +
	"\x05delay\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x05delay\x12\x12\n" +
	"\x04dead\x18\x05 \x01(\bR\x04dead\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"~\n" +
	"\rExtendRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x126\n" +
	"\textend_by\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bextendBy\"d\n" +
	"\vAckResponse\x12\x14\n" +
	"\x05acked\x18\x01 \x01(\rR\x05acked\x12?\n" +
	"\tconflicts\x18\x02 \x03(\v2!.hookaido.worker.v1.LeaseConflictR\tconflicts\"m\n" +
	"\fNackResponse\x12\x1c\n" +
	"\tsucceeded\x18\x01 \x01(\rR\tsucceeded\x12?\n" +
	"\tconflicts\x18\x02 \x03(\v2!.hookaido.worker.v1.LeaseConflictR\tconflicts\"D\n" +
	"\rLeaseConflict\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x18\n" +
	"\aexpired\x18\x02 \x01(\bR\aexpired2\xbb\x02\n" +
	"\rWorkerService\x12R\n" +
	"\aDequeue\x12\".hookaido.worker.v1.DequeueRequest\x1a#.hookaido.worker.v1.DequeueResponse\x12F\n" +
	"\x03Ack\x12\x1e.hookaido.worker.v1.AckRequest\x1a\x1f.hookaido.worker.v1.AckResponse\x12I\n" +
	"\x04Nack\x12\x1f.hookaido.worker.v1.NackRequest\x1a .hookaido.worker.v1.NackResponse\x12C\n" +
	"\x06Extend\x12!.hookaido.worker.v1.ExtendRequest\x1a\x16.google.protobuf.EmptyBFZDgithub.com/nuetzliches/hookaido/internal/workerapi/proto;workerapipbb\x06proto3"

var (
	file_workerapi_proto_rawDescOnce sync.Once
	file_workerapi_proto_rawDescData []byte
)

func file_workerapi_proto_rawDescGZIP() []byte {
	file_workerapi_proto_rawDescOnce.Do(func() {
		file_workerapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workerapi_proto_rawDesc), len(file_workerapi_proto_rawDesc)))
	})
	return file_workerapi_proto_rawDescData
}

var file_workerapi_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_workerapi_proto_goTypes = []any{
	(*DequeueRequest)(nil),        // 0: hookaido.worker.v1.DequeueRequest
	(*DequeueResponse)(nil),       // 1: hookaido.worker.v1.DequeueResponse
	(*DequeueItem)(nil),           // 2: hookaido.worker.v1.DequeueItem
	(*AckRequest)(nil),            // 3: hookaido.worker.v1.AckRequest
	(*NackRequest)(nil),           // 4: hookaido.worker.v1.NackRequest
	(*ExtendRequest)(nil),         // 5: hookaido.worker.v1.ExtendRequest
	(*AckResponse)(nil),           // 6: hookaido.worker.v1.AckResponse
	(*NackResponse)(nil),          // 7: hookaido.worker.v1.NackResponse
	(*LeaseConflict)(nil),         // 8: hookaido.worker.v1.LeaseConflict
	nil,                           // 9: hookaido.worker.v1.DequeueItem.HeadersEntry
	nil,                           // 10: hookaido.worker.v1.DequeueItem.TraceEntry
	(*durationpb.Duration)(nil),   // 11: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_workerapi_proto_depIdxs = []int32{
	11, // 0: hookaido.worker.v1.DequeueRequest.max_wait:type_name -> google.protobuf.Duration
	11, // 1: hookaido.worker.v1.DequeueRequest.lease_ttl:type_name -> google.protobuf.Duration
	2,  // 2: hookaido.worker.v1.DequeueResponse.items:type_name -> hookaido.worker.v1.DequeueItem
	12, // 3: hookaido.worker.v1.DequeueItem.received_at:type_name -> google.protobuf.Timestamp
	12, // 4: hookaido.worker.v1.DequeueItem.next_run_at:type_name -> google.protobuf.Timestamp
	9,  // 5: hookaido.worker.v1.DequeueItem.headers:type_name -> hookaido.worker.v1.DequeueItem.HeadersEntry
	10, // 6: hookaido.worker.v1.DequeueItem.trace:type_name -> hookaido.worker.v1.DequeueItem.TraceEntry
	11, // 7: hookaido.worker.v1.NackRequest.delay:type_name -> google.protobuf.Duration
	11, // 8: hookaido.worker.v1.ExtendRequest.extend_by:type_name -> google.protobuf.Duration
	8,  // 9: hookaido.worker.v1.AckResponse.conflicts:type_name -> hookaido.worker.v1.LeaseConflict
	8,  // 10: hookaido.worker.v1.NackResponse.conflicts:type_name -> hookaido.worker.v1.LeaseConflict
	0,  // 11: hookaido.worker.v1.WorkerService.Dequeue:input_type -> hookaido.worker.v1.DequeueRequest
	3,  // 12: hookaido.worker.v1.WorkerService.Ack:input_type -> hookaido.worker.v1.AckRequest
	4,  // 13: hookaido.worker.v1.WorkerService.Nack:input_type -> hookaido.worker.v1.NackRequest
	5,  // 14: hookaido.worker.v1.WorkerService.Extend:input_type -> hookaido.worker.v1.ExtendRequest
	1,  // 15: hookaido.worker.v1.WorkerService.Dequeue:output_type -> hookaido.worker.v1.DequeueResponse
	6,  // 16: hookaido.worker.v1.WorkerService.Ack:output_type -> hookaido.worker.v1.AckResponse
	7,  // 17: hookaido.worker.v1.WorkerService.Nack:output_type -> hookaido.worker.v1.NackResponse
	13, // 18: hookaido.worker.v1.WorkerService.Extend:output_type -> google.protobuf.Empty
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_workerapi_proto_init() }
func file_workerapi_proto_init() {
	if File_workerapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workerapi_proto_rawDesc), len(file_workerapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workerapi_proto_goTypes,
		DependencyIndexes: file_workerapi_proto_depIdxs,
		MessageInfos:      file_workerapi_proto_msgTypes,
	}.Build()
	File_workerapi_proto = out.File
	file_workerapi_proto_goTypes = nil
	file_workerapi_proto_depIdxs = nil
}
