name: Bug Report
description: Report a reproducible defect in Hookaido.
title: "[bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        **Do not report security vulnerabilities in public issues.**
        Use private advisory reporting instead:
        https://github.com/nuetzliches/hookaido/security/advisories/new

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: Short description of the bug.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      options:
        - Ingress
        - Pull API
        - Admin API
        - Queue (SQLite/Memory)
        - Dispatcher (Push Delivery)
        - Config DSL / Compile
        - MCP
        - Observability
        - CLI
        - Docs
        - Release / CI
        - Other
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Include exact steps and inputs so maintainers can reproduce.
      placeholder: |
        1. Start Hookaido with config ...
        2. Send request ...
        3. Call endpoint ...
        4. Observe error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Logs / Error Output
      description: Paste relevant logs, stack traces, or HTTP responses. Remove secrets.
      render: text
      placeholder: Relevant output only (no secrets).
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Minimal Config to Reproduce (Optional)
      description: Share a reduced Hookaidofile snippet if possible. Remove secrets.
      render: hcl
      placeholder: Minimal config snippet that reproduces the issue.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Runtime and platform details.
      placeholder: |
        - Hookaido version:
        - OS:
        - Deployment mode:
        - Queue backend:
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-Submission Check
      options:
        - label: I checked existing issues and this is not a duplicate.
          required: true
        - label: I removed credentials, tokens, and secrets from logs/config.
          required: true
